env:
  browser: true
  es6: true
  jest/globals: true

extends:
  - 'eslint:recommended'
  - 'plugin:jest/recommended'

parser: babel-eslint

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins:
  - react
  - babel
  - jest

globals:
  process: readable

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - single
  semi:
    - warn
    - always
